cryticArgs: # If we add more dependencies they will need to be added as symlinks here!
  [
    "--solc-remaps",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/ @openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/ @chainlink/contracts/=node_modules/@chainlink/contracts/ @chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/",
  ]
